import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Yasir Protfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <header>
          <Navbar></Navbar>
        </header>
        <Toaster position="top-right" />
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
